baseUrl: "https://shiokazehs.jp/"
languageCode: "ja-jp"
title: "小樽潮風高校文化祭「しおばな祭」"
theme: "sakura"
params:
  author: "Nectarition"
  since: 2022
  event:
    logo: "/logo.svg"
    genre: "小樽潮風高校文化祭"
    name: "しおばな祭"
    subTitle: "TOKYO6キャラクターオンリーイベント"
    date: "2022年5月7日(土)"
    place: "川崎市産業振興会館 4階企画展示場"
    illustrator: "みなつき"
  TwitterScreenName: "nct_kohatabe"
  GoogleAnalyticsMeasuringId: "G-L018P3DWJH"

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
